const mainHeader=document.getElementById('mainHeader'),
      librarySetsBtn=document.getElementById('librarySetsBtn'),
      setsBackBtn=document.getElementById('setsBackBtn'),
      editorBackBtn=document.getElementById('editorBackBtn'),
      newSetName=document.getElementById('newSetName'),
      createSetBtn=document.getElementById('createSetBtn'),
      setCards=document.getElementById('setCards'),
      editorTitle=document.getElementById('editorTitle'),
      setOrder=document.getElementById('setOrder'),
      songPicker=document.getElementById('songPicker'),
      playSetBtn=document.getElementById('playSetBtn'),
      songBackBtn=document.getElementById('songBackBtn'),
      prevSetSongBtn=document.getElementById('prevSetSongBtn'),
      nextSetSongBtn=document.getElementById('nextSetSongBtn'),
      setContext=document.getElementById('setContext');
const grid=document.getElementById('grid'), audio=document.getElementById('audio'), content=document.getElementById('content');
const play=document.getElementById('play'), seek=document.getElementById('seek'),
      time=document.getElementById('time'), dur=document.getElementById('dur'),
      take=document.getElementById('take'), loopRead=document.getElementById('loopRead'),
      loopBtn=document.getElementById('loopBtn'), setA=document.getElementById('setA'),
      setB=document.getElementById('setB'), clearLoopBtn=document.getElementById('clearLoopBtn'), transposeBox=document.getElementById('transposeBox'),
      key=document.getElementById('key'), minus=document.getElementById('minus'),
      plus=document.getElementById('plus'), boldBtn=document.getElementById('boldBtn'),
      colBtn=document.getElementById('colBtn'), barTitle=document.getElementById('barTitle'),
      titleEl=document.getElementById('title'), by=document.getElementById('by'),
      links=document.getElementById('links'), search=document.getElementById('search');
let current=null, offset=0, fs=21, bold=false, two=true, loopA=null, loopB=null, looping=false;
let setLists=[], editingSetId=null, activeSetId=null, activeSetIndex=-1;
const pitch={'C':0,'B#':0,'C#':1,'Db':1,'D':2,'D#':3,'Eb':3,'E':4,'Fb':4,'E#':5,'F':5,'F#':6,'Gb':6,'G':7,'G#':8,'Ab':8,'A':9,'A#':10,'Bb':10,'B':11,'Cb':11};
const sharp=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'], flat=['C','Db','D','Eb','E','F','Gb','G','Ab','A','Bb','B'];
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('on'));document.getElementById(id).classList.add('on');mainHeader.style.display='flex';scrollTo(0,0)}
function renderLibrary(q=''){grid.innerHTML='';SONGS.filter(s=>s.toLowerCase().includes(q.toLowerCase())).forEach((s,i)=>{const m=M[s];let bits=[];if(m.audio.length)bits.push(m.audio.length>1?`${m.audio.length} recordings`:'recording');if(m.sheets.length)bits.push((m.type==='viola'||m.type==='notation'||m.type==='notation_image')?'notation / score':'sheet');if(m.type==='editable'||m.type==='editable_source')bits.push('transposable');let b=document.createElement('button');b.className='song';b.onclick=()=>openSong(s);b.innerHTML=`<span class=num>${String(i+1).padStart(2,'0')}</span><span><div class=st>${s}</div><div class=meta>${bits.length?bits.join(' • '):'awaiting resource'}</div></span><span class=badge>${bits.length?'● READY':''}</span>`;grid.appendChild(b)})}
search.oninput=e=>renderLibrary(e.target.value);
function openSong(s){current=s;offset=0;clearLoop();show('song');barTitle.textContent=titleEl.textContent=s;const m=M[s];by.textContent=m.note||'';links.innerHTML='';m.sheets.forEach((f,i)=>{let b=document.createElement('button');b.className='ctl';b.textContent=(m.sheetLabels&&m.sheetLabels[i])?m.sheetLabels[i]:(m.sheets.length>1?`Sheet ${i+1}`:'Open Sheet');b.onclick=()=>window.open(encodeURI('music/'+f),'_blank');links.appendChild(b)});take.innerHTML='';if(m.audio.length>1){take.style.display='block';m.audio.forEach((f,i)=>{let o=document.createElement('option');o.value=f;o.textContent=prettyRecording(f,i);take.appendChild(o)});take.onchange=()=>loadAudio(take.value)}else take.style.display='none';loadAudio(m.audio[0]||'');const edit=(m.type==='editable'||m.type==='editable_source');transposeBox.style.display=edit?'flex':'none';minus.style.display=plus.style.display=boldBtn.style.display=colBtn.style.display=edit?'inline-block':'none';if(m.type==='editable'){renderLight()}else if(m.type==='editable_source'){renderSourceEditable(s)}else if(m.type==='notation_image'&&m.image){content.innerHTML=`<img class="notationImage" src="${encodeURI('music/'+m.image)}" alt="${esc(s)} notation">`}else if(m.sheets.length){content.innerHTML=`<object class=pdfbox data="${encodeURI('music/'+m.sheets[0])}" type="application/pdf"><div class=placeholder>Use the Open Sheet button above if your browser does not display the PDF here.</div></object>`}else{content.innerHTML=`<div class=placeholder>${m.audio.length?'<b>Practice recording'+(m.audio.length>1?'s are':' is')+' linked below.</b><br><br>':''}No matching sheet file has been supplied for this song yet.</div>`}updateSetNav()}
function prettyRecording(f,i){return f.replace(/\.(m4a|mp3|wav)$/i,'').replace(/_/g,' ')}
function loadAudio(f){audio.pause();audio.src=f?'audio/'+encodeURIComponent(f):'';play.textContent='▶';seek.value=0;time.textContent='0:00';dur.textContent='0:00';clearLoop()}
function back(){audio.pause();if(activeSetId){show('setEditor');renderSetEditor(activeSetId)}else{show('library')}}
function chordParts(tok){return tok.match(/^([(\[]?)([A-G](?:#|b|♭|♯)?(?:m|maj|min|dim|aug|sus|add)?\d*(?:\([#b]?\d+\))?(?:\/[A-G](?:#|b|♭|♯)?)?)([)\],.;:]?)$/)}
function normalizeAcc(s){return s.replaceAll('♭','b').replaceAll('♯','#')}
function keyName(){let n=(pitch['F']+offset+120)%12;return (offset===0?flat:sharp)[n]}
function transposeChord(ch){ch=normalizeAcc(ch);const parts=ch.split('/');const mm=parts[0].match(/^([A-G](?:#|b)?)(.*)$/);if(!mm)return ch;let n=(pitch[mm[1]]+offset+120)%12;const flatish=/b/.test(ch)||['F','Bb','Eb','Ab','Db','Gb'].includes(keyName());let out=(flatish?flat:sharp)[n]+mm[2];if(parts.length>1){const bm=parts[1].match(/^([A-G](?:#|b)?)(.*)$/);if(bm){let bn=(pitch[bm[1]]+offset+120)%12;out+='/'+(flatish?flat:sharp)[bn]+bm[2]}}return out}
function outChord(ch){return transposeChord(ch)}
function renderSourceLine(line){const pieces=line.split(/(\s+)/),words=pieces.filter(x=>x.trim()),cps=words.filter(x=>chordParts(x));const heavy=cps.length>=2||(words.length<=4&&cps.length>=1);return pieces.map(tok=>{if(!tok.trim())return esc(tok);const cp=chordParts(tok);if(!cp)return esc(tok);const core=normalizeAcc(cp[2]),complex=core.length>1;if(!(heavy||complex))return esc(tok);return `<span class="chord-token">${esc(cp[1])}${esc(transposeChord(core))}${esc(cp[3])}</span>`}).join('')}
function renderSourceEditable(song){const src=EDITABLE[song];if(!src){content.innerHTML='<div class=placeholder>Editable text unavailable.</div>';return}let h='<div id=music class="music sourceMusic">';src.text.split('\n').forEach(line=>{h+=`<div class="sourceLine">${renderSourceLine(line)||'&nbsp;'}</div>`});h+='</div>';content.innerHTML=h;music.style.fontSize=fs+'px';music.style.fontWeight=bold?'700':'400';music.style.columnCount=two?'2':'1';key.textContent=(offset>0?'+':'')+offset}
function renderLight(){let h='';LIGHT.forEach(sec=>{h+=`<div class=section>${sec[0]}</div>`;sec[1].forEach(r=>{h+=`<div class=row><div class=chords>${r[0].map(c=>`<span>${outChord(c)}</span>`).join('')}</div><div class=lyrics>${esc(r[1])}</div></div>`});});content.innerHTML=`<div id=music class=music>${h}</div>`;music.style.fontSize=fs+'px';music.style.fontWeight=bold?'700':'400';music.style.columnCount=two?'2':'1';key.textContent=keyName()}
function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function rerenderCurrent(){if(current==='Light Show')renderLight();else if(M[current]&&M[current].type==='editable_source')renderSourceEditable(current)}
function transpose(d){offset=Math.max(-11,Math.min(11,offset+d));rerenderCurrent()}function resetTranspose(){offset=0;rerenderCurrent()}function font(d){fs=Math.max(12,Math.min(36,fs+d));rerenderCurrent()}function toggleBold(){bold=!bold;boldBtn.classList.toggle('primary',bold);rerenderCurrent()}function toggleCols(){two=!two;colBtn.textContent=two?'2 Columns':'1 Column';colBtn.classList.toggle('primary',two);rerenderCurrent()}
function loadSetLists(){try{setLists=JSON.parse(localStorage.getItem('oxbowsSetLists')||'[]')}catch(e){setLists=[]}}
function saveSetLists(){localStorage.setItem('oxbowsSetLists',JSON.stringify(setLists))}
function makeSetId(){return 'set-'+Date.now()+'-'+Math.random().toString(36).slice(2,7)}
function makeButton(label,cls,fn){const b=document.createElement('button');b.type='button';b.className=cls||'miniBtn';b.textContent=label;b.addEventListener('click',fn);return b}
function createSetList(){const name=(newSetName.value||'').trim();if(!name){alert('Give the set list a name first.');return}const s={id:makeSetId(),name,songs:[]};setLists.push(s);saveSetLists();newSetName.value='';renderSetCards();openSetEditor(s.id)}
function renderSetCards(){setCards.innerHTML='';if(!setLists.length){setCards.innerHTML='<div class="placeholder">No set lists yet. Create one above.</div>';return}setLists.forEach(s=>{const card=document.createElement('div');card.className='setCard';const top=document.createElement('div');top.className='setCardTop';const text=document.createElement('div');const t=document.createElement('div');t.className='setCardTitle';t.textContent=s.name;const meta=document.createElement('div');meta.className='setCardMeta';meta.textContent=`${s.songs.length} song${s.songs.length===1?'':'s'}`;text.append(t,meta);const acts=document.createElement('div');acts.className='setCardActions';acts.append(makeButton('Edit','miniBtn',()=>openSetEditor(s.id)),makeButton('Play','miniBtn primary',()=>playSet(s.id)),makeButton('Delete','miniBtn',()=>deleteSetList(s.id)));top.append(text,acts);card.append(top);setCards.append(card)})}
function deleteSetList(id){const s=setLists.find(x=>x.id===id);if(!s)return;if(!confirm(`Delete "${s.name}"?`))return;setLists=setLists.filter(x=>x.id!==id);saveSetLists();if(activeSetId===id){activeSetId=null;activeSetIndex=-1}renderSetCards()}
function openSetEditor(id){editingSetId=id;activeSetId=null;activeSetIndex=-1;show('setEditor');renderSetEditor(id)}
function renderSetEditor(id){const s=setLists.find(x=>x.id===id);if(!s){show('sets');renderSetCards();return}editingSetId=id;editorTitle.textContent=s.name;setOrder.innerHTML='';songPicker.innerHTML='';if(!s.songs.length)setOrder.innerHTML='<div class="placeholder">Add songs from the right.</div>';s.songs.forEach((title,i)=>{const row=document.createElement('div');row.className='setRow';const nm=document.createElement('span');nm.className='setRowTitle';nm.textContent=`${i+1}. ${title}`;const up=makeButton('↑','miniBtn',()=>moveSetSong(id,i,-1));up.disabled=i===0;const down=makeButton('↓','miniBtn',()=>moveSetSong(id,i,1));down.disabled=i===s.songs.length-1;const rem=makeButton('Remove','miniBtn',()=>removeSetSong(id,i));row.append(nm,up,down,rem);setOrder.append(row)});const existing=new Set(s.songs);SONGS.forEach(title=>{const row=document.createElement('div');row.className='songPick';const nm=document.createElement('span');nm.className='songPickTitle';nm.textContent=title;const added=existing.has(title);const act=makeButton(added?'Added':'Add',added?'miniBtn':'miniBtn primary',()=>added?removeSongByTitle(id,title):addSetSong(id,title));row.append(nm,act);songPicker.append(row)})}
function addSetSong(id,title){const s=setLists.find(x=>x.id===id);if(!s)return;if(!s.songs.includes(title))s.songs.push(title);saveSetLists();renderSetEditor(id);renderSetCards()}
function removeSongByTitle(id,title){const s=setLists.find(x=>x.id===id);if(!s)return;s.songs=s.songs.filter(x=>x!==title);saveSetLists();renderSetEditor(id);renderSetCards()}
function removeSetSong(id,index){const s=setLists.find(x=>x.id===id);if(!s)return;s.songs.splice(index,1);saveSetLists();renderSetEditor(id);renderSetCards()}
function moveSetSong(id,index,delta){const s=setLists.find(x=>x.id===id);if(!s)return;const ni=index+delta;if(ni<0||ni>=s.songs.length)return;[s.songs[index],s.songs[ni]]=[s.songs[ni],s.songs[index]];saveSetLists();renderSetEditor(id)}
function playSet(id){const s=setLists.find(x=>x.id===id);if(!s||!s.songs.length){alert('Add at least one song to this set list first.');return}activeSetId=id;activeSetIndex=0;editingSetId=id;openSong(s.songs[0]);updateSetNav()}
function openSongFromSet(index){const s=setLists.find(x=>x.id===activeSetId);if(!s||index<0||index>=s.songs.length)return;activeSetIndex=index;openSong(s.songs[index]);updateSetNav()}
function updateSetNav(){const s=setLists.find(x=>x.id===activeSetId);if(!s){prevSetSongBtn.style.display='none';nextSetSongBtn.style.display='none';setContext.style.display='none';return}prevSetSongBtn.style.display='inline-block';nextSetSongBtn.style.display='inline-block';setContext.style.display='inline-block';prevSetSongBtn.disabled=activeSetIndex<=0;nextSetSongBtn.disabled=activeSetIndex>=s.songs.length-1;setContext.textContent=`${s.name} • ${activeSetIndex+1}/${s.songs.length}`}
function leaveSetContext(){activeSetId=null;activeSetIndex=-1;updateSetNav()}
let loopTimer=null;
function markA(){if(!audio.src){alert('Choose a recording first.');return}loopA=audio.currentTime;if(loopB!==null&&loopB<=loopA)loopB=null;stopLoop(false);updateLoopUI()}
function markB(){if(!audio.src){alert('Choose a recording first.');return}loopB=audio.currentTime;if(loopA===null){loopA=Math.max(0,loopB-5)}else if(loopB<=loopA){loopA=Math.max(0,loopB-5)}stopLoop(false);updateLoopUI()}
function startLoopWatcher(){stopLoopWatcher();loopTimer=setInterval(()=>{if(!looping||loopA===null||loopB===null)return;if(audio.currentTime>=loopB||audio.currentTime<loopA-0.05){audio.currentTime=loopA;if(audio.paused){const p=audio.play();if(p&&p.catch)p.catch(()=>{})}}},35)}
function stopLoopWatcher(){if(loopTimer!==null){clearInterval(loopTimer);loopTimer=null}}
function playLoop(){if(loopA===null||loopB===null||loopB<=loopA){alert('Set the loop first: move to the start and tap Set A, move to the end and tap Set B, then tap ▶ Play A–B.');return}if(looping){stopLoop(true);return}looping=true;audio.currentTime=loopA;const promise=audio.play();if(promise&&promise.catch){promise.catch(err=>{looping=false;updateLoopUI();alert('The browser blocked playback. Tap the main ▶ button once, then try Play A–B again.')})}play.textContent='❚❚';startLoopWatcher();updateLoopUI()}
function stopLoop(pauseAudio=true){looping=false;stopLoopWatcher();if(pauseAudio)audio.pause();if(pauseAudio)play.textContent='▶';updateLoopUI()}
function clearLoop(){stopLoop(false);loopA=null;loopB=null;updateLoopUI()}
function updateLoopUI(){if(!loopRead||!loopBtn||!setA||!setB)return;loopRead.textContent=`A ${loopA===null?'—':fmt(loopA)} / B ${loopB===null?'—':fmt(loopB)}`;loopBtn.textContent=looping?'■ Stop A–B':'▶ Play A–B';loopBtn.classList.toggle('on',looping);loopBtn.classList.toggle('ready',!looping&&loopA!==null&&loopB!==null&&loopB>loopA);setA.classList.toggle('on',loopA!==null);setB.classList.toggle('on',loopB!==null)}
librarySetsBtn.addEventListener('click',()=>{loadSetLists();renderSetCards();show('sets')});setsBackBtn.addEventListener('click',()=>{leaveSetContext();show('library')});editorBackBtn.addEventListener('click',()=>{leaveSetContext();renderSetCards();show('sets')});createSetBtn.addEventListener('click',createSetList);newSetName.addEventListener('keydown',e=>{if(e.key==='Enter')createSetList()});playSetBtn.addEventListener('click',()=>{if(editingSetId)playSet(editingSetId)});songBackBtn.addEventListener('click',back);prevSetSongBtn.addEventListener('click',()=>openSongFromSet(activeSetIndex-1));nextSetSongBtn.addEventListener('click',()=>openSongFromSet(activeSetIndex+1));setA.addEventListener('click',markA);setB.addEventListener('click',markB);loopBtn.addEventListener('click',playLoop);clearLoopBtn.addEventListener('click',clearLoop);
play.onclick=()=>{if(!audio.src){alert('No recording supplied for this song yet.');return}if(audio.paused){if(looping&&loopA!==null&&loopB!==null&&(audio.currentTime<loopA||audio.currentTime>=loopB))audio.currentTime=loopA;const p=audio.play();if(p&&p.catch)p.catch(()=>{});play.textContent='❚❚'}else{audio.pause();play.textContent='▶'}};
audio.onended=()=>{if(looping&&loopA!==null&&loopB!==null){audio.currentTime=loopA;const p=audio.play();if(p&&p.catch)p.catch(()=>{})}else{play.textContent='▶'}};
audio.ontimeupdate=()=>{if(audio.duration){seek.value=100*audio.currentTime/audio.duration;time.textContent=fmt(audio.currentTime);dur.textContent=fmt(audio.duration)}};
seek.oninput=e=>{if(audio.duration){audio.currentTime=audio.duration*e.target.value/100;if(looping&&loopA!==null&&loopB!==null&&(audio.currentTime<loopA||audio.currentTime>loopB)){stopLoop(false)}}};
function fmt(x){return Math.floor(x/60)+':'+String(Math.floor(x%60)).padStart(2,'0')}
loadSetLists();renderLibrary();renderSetCards();updateLoopUI();mainHeader.style.display='flex';