import wasmURL from '../node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.wasm?url';
import mjsURL from '../node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.mjs?url';
import {steps} from './music.js';
import {contextualizeDraft} from './scan-context.js';
import {durationFor} from './rhythm.js';
import {binary,prepareImage,rhythmIssues} from './image-preprocess.js';
let engine;
export async function loadEngine(progress){if(engine)return engine;progress('Loading note recognition model (38 MB, first use)…');const ort=await import('onnxruntime-web/wasm');ort.env.wasm.wasmPaths={wasm:new URL(wasmURL,location.href).href,mjs:new URL(mjsURL,location.href).href};ort.env.wasm.numThreads=1;ort.env.wasm.proxy=false;const chunks=await Promise.all(['00','01'].map(async n=>{const r=await fetch(import.meta.env.BASE_URL+'models/notes-'+n);if(!r.ok)throw Error('The recognition model could not be loaded. Please try again.');return new Uint8Array(await r.arrayBuffer());}));const data=new Uint8Array(chunks[0].length+chunks[1].length);data.set(chunks[0]);data.set(chunks[1],chunks[0].length);const session=await ort.InferenceSession.create(data,{executionProviders:['wasm'],graphOptimizationLevel:'all'});engine={ort,session};return engine;}
export function findStaves(image){const w=image.width,h=image.height,b= binary(image),projection=new Float32Array(h);for(let y=0;y<h;y++){let sum=0;for(let x=0;x<w;x++)sum+=b[y*w+x];projection[y]=sum;}const max=Math.max(...projection),rows=[];for(let y=0;y<h;y++)if(projection[y]>Math.max(w*.22,max*.42)){let ys=0,weight=0;while(y<h&&projection[y]>Math.max(w*.20,max*.35)){ys+=y*projection[y];weight+=projection[y];y++;}rows.push(ys/weight);}const found=[];for(let i=0;i<rows.length-4;i++){const r=rows.slice(i,i+5),g=(r[4]-r[0])/4;if(g<4||g>65)continue;if(r.slice(1).every((y,j)=>Math.abs(y-r[j]-g)<Math.max(1.7,g*.18))){let left=w,right=0;for(let x=0;x<w;x++){let sum=0;for(const y of r)sum+=b[Math.round(y)*w+x];if(sum>=3){left=Math.min(left,x);right=x;}}found.push({lines:r,gap:g,left,right});i+=4;}}return found;}
function components(mask,w,h){const seen=new Uint8Array(mask.length),result=[],queue=new Int32Array(mask.length);for(let i=0;i<mask.length;i++){if(!mask[i]||seen[i])continue;let head=0,tail=1;queue[0]=i;seen[i]=1;let minX=w,maxX=0,minY=h,maxY=0,sx=0,sy=0;while(head<tail){const k=queue[head++],x=k%w,y=Math.floor(k/w);minX=Math.min(x,minX);maxX=Math.max(x,maxX);minY=Math.min(y,minY);maxY=Math.max(y,maxY);sx+=x;sy+=y;for(const [dx,dy] of [[-1,0],[1,0],[0,-1],[0,1]]){const xx=x+dx,yy=y+dy,j=yy*w+xx;if(xx>=0&&xx<w&&yy>=0&&yy<h&&!seen[j]&&mask[j]){seen[j]=1;queue[tail++]=j;}}}result.push({x:sx/tail,y:sy/tail,minX,maxX,minY,maxY,area:tail});}return result;}
export async function recognize(canvas,options,progress,signal,inferenceEngine=loadEngine){progress('Straightening the page and balancing lighting…');const prepared=prepareImage(canvas);canvas=prepared.canvas;let ctx=canvas.getContext('2d',{willReadFrequently:true}),image=ctx.getImageData(0,0,canvas.width,canvas.height);let staves=findStaves(image);if(!staves.length)throw Error('No straight five-line staves found. Crop to a clear printed melody, straighten the page, or import PlayScore MusicXML.');const avg=staves.reduce((s,a)=>s+a.gap,0)/staves.length,scale=12/avg;if(Math.abs(scale-1)>.08){const c=typeof OffscreenCanvas!=='undefined'?new OffscreenCanvas(1,1):document.createElement('canvas');c.width=Math.round(canvas.width*scale);c.height=Math.round(canvas.height*scale);if(c.width*c.height>12e6)throw Error('This page is too dense. Crop to fewer systems and try again.');c.getContext('2d').drawImage(canvas,0,0,c.width,c.height);canvas=c;ctx=c.getContext('2d',{willReadFrequently:true});image=ctx.getImageData(0,0,c.width,c.height);staves=findStaves(image);}const {session,ort}=await inferenceEngine(progress);const w=canvas.width,h=canvas.height,bin=binary(image),draft=[],boxes=[];let total=staves.reduce((s,a)=>s+Math.ceil((a.right-a.left)/224),0),done=0;
for(let si=0;si<staves.length;si++){const staff=staves[si],g=staff.gap,stripTop=Math.max(0,Math.round(staff.lines[0]-g*5)),stripBottom=Math.min(h,Math.round(staff.lines[4]+g*5)),sh=stripBottom-stripTop,prob=new Float32Array(w*sh),counts=new Uint8Array(w*sh);for(let x0=Math.max(0,staff.left-20);x0<staff.right;x0+=224){if(signal?.aborted)throw Error('Scan cancelled.');progress(`Reading staff ${si+1} of ${staves.length} · ${Math.min(99,Math.round(done/total*100))}%`);await new Promise(r=>setTimeout(r,0));const y0=Math.round((staff.lines[0]+staff.lines[4])/2-144),input=new Uint8Array(288*288*3);input.fill(255);for(let yy=0;yy<288;yy++)for(let xx=0;xx<288;xx++){const x=x0+xx,y=y0+yy;if(x>=0&&y>=0&&x<w&&y<h){const pos=(y*w+x)*4,j=(yy*288+xx)*3;input[j]=image.data[pos+2];input[j+1]=image.data[pos+1];input[j+2]=image.data[pos];}}const tensor=new ort.Tensor('uint8',input,[1,288,288,3]);const outputs=await session.run({[session.inputNames[0]]:tensor});const out=outputs[session.outputNames[0]].data;for(let yy=0;yy<288;yy++){const y=y0+yy-stripTop;if(y<0||y>=sh)continue;for(let xx=0;xx<288;xx++){const x=x0+xx;if(x<0||x>=w)continue;const i=y*w+x;prob[i]+=out[(yy*288+xx)*4+2];counts[i]++;}}Object.values(outputs).forEach(t=>t.dispose());tensor.dispose();done++;}
const mask=new Uint8Array(prob.length);for(let i=0;i<mask.length;i++)mask[i]=prob[i]/(counts[i]||1)>.4?1:0;const found=components(mask,w,sh).filter(c=>c.area>g*g*.12&&c.area<g*g*2.2&&c.maxX-c.minX>g*.45&&c.maxX-c.minX<g*2.2&&c.maxY-c.minY<g*1.8).map(c=>({...c,y:c.y+stripTop})).sort((a,b)=>a.x-b.x);const bars=[];for(let x=Math.round(staff.left+g*2);x<staff.right-2;x++){let hits=0;for(let y=Math.round(staff.lines[0]);y<=staff.lines[4];y++)hits+=bin[y*w+x];if(hits>g*3.7&&!found.some(n=>Math.abs(n.x-x)<g*.9)){if(!bars.length||x-bars[bars.length-1]>g*.8)bars.push(x);}}
let current=[],barIndex=0;for(const n of found){while(barIndex<bars.length&&n.x>bars[barIndex]){if(current.length){draft.push(current);current=[];}barIndex++;}const position=(staff.lines[4]-n.y)/(g/2),offset=Math.round(position),base=options.clef==='alto'?3*7+3:4*7+2,d=base+offset,step=steps[((d%7)+7)%7],octave=Math.floor(d/7),sharpOrder=['F','C','G','D','A','E','B'],flatOrder=['B','E','A','D','G','C','F'];const alter=options.fifths>0&&sharpOrder.slice(0,options.fifths).includes(step)?1:options.fifths<0&&flatOrder.slice(0,-options.fifths).includes(step)?-1:0;const pc={C:0,D:2,E:4,F:5,G:7,A:9,B:11}[step];const center=Math.round(n.y-stripTop)*w+Math.round(n.x),confidence=prob[center]/(counts[center]||1);const review=Math.abs(position-offset)>.28?'Pitch lies between staff positions':confidence<.68?'Uncertain notehead':null;current.push({midi:12*(octave+1)+pc+alter,pitch:{step,octave,alter},duration:durationFor(n,bin,w,h,g,staff),review});boxes.push({x:n.x/scale,y:n.y/scale});}if(current.length)draft.push(current);}
if(!draft.length)throw Error('No readable noteheads found. Try a sharper, closer image or PlayScore MusicXML.');const interpreted=options.interpretation==='context'?contextualizeDraft(draft,options):{draft,corrections:[]};return {...interpreted,staves:staves.length,notes:draft.reduce((s,m)=>s+m.length,0),boxes,angle:prepared.angle,issues:rhythmIssues(interpreted.draft,options.beats,options.beatType)};}
